### ISSUE TITLE
1.3.0 release checklist

### ISSUE THREAD

**Issue by lukebakken** [pika/pika#1363]
- [ ] Review all example code (especially in the `.rst` files) :tada:

**Comment by alfawal** [comment]
I am not sure about the current state of this repo.
Can you adjust the checklist with:
* [ ] Add pre-commit config including flake, black formatter, isort etc.
* [ ] Update the docs taking care of python3 support

**Comment by lukebakken** [comment]
> Update the docs taking care of python3 support

Pika has been Python 3 compatible for some time now.

> Add pre-commit config including flake, black formatter, isort etc.

If people would like to add a pre-commit, it's on them. This is our official formatting guide: [link](https://github.com/pika/pika/blob/main/CONTRIBUTING.md#code-formatting)

**Comment by alfawal** [comment]
Some parts of the docs are using Python 2's methods/docs urls, shouldn't we update them to use 3 instead? or both?

**Comment by lukebakken** [comment]
> Some parts of the docs are using Python 2's methods/docs urls, shouldn't we update them to use 3 instead? or mention both?

Thanks for noticing. We'd appreciate a pull request to do so. I'll make a note of it for 2.0

**Comment by alfawal** [comment]
Sorry if I am using this issue for unrelated questions.
Shouldn't you drop the support for python2?
I think the code looks ugly with it and is hard to read, the structure of the repo code looks good but it needs to be modernized in someway, don't you agree?

**Comment by lukebakken** [comment]
Python 2 support was dropped a while ago and a search of this repo's history would have shown you that.

If you have specific code changes that are more than cosmetic, feel free to open PRs to address them.
